[package]
name = "atrium-api"
version = "0.1.1"
authors = ["sugyan <sugi1982+github@gmail.com>"]
edition = "2021"
description = "API library for AT Protocol (Bluesky)"
documentation = "https://docs.rs/atrium-api"
readme = "README.md"
repository = "https://github.com/sugyan/atrium"
license = "MIT"
keywords = ["atproto", "bluesky"]


[dependencies]
async-trait = "0.1.68"
http = "0.2.9"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
serde_urlencoded = "0.7.1"

[dev-dependencies]
tokio = { version = "1.28.0", features = ["macros", "rt"] }
