[package]
name = "atrium-api"
version = "0.4.0"
authors = ["sugyan <sugi1982+github@gmail.com>"]
edition = "2021"
description = "API library for AT Protocol (Bluesky)"
documentation = "https://docs.rs/atrium-api"
readme = "README.md"
repository = "https://github.com/sugyan/atrium"
license = "MIT"
keywords = ["atproto", "bluesky"]


[dependencies]
atrium-xrpc = "0.3"
async-trait = "0.1.68"
cid = { version = "0.10.1", features = ["serde-codec"] }
http = "0.2.9"
serde = { version = "1.0.160", features = ["derive"] }
serde_bytes = "0.11.9"

[dev-dependencies]
tokio = { version = "1.28.0", features = ["macros", "rt-multi-thread"] }
