# Rustfmt configuration file

# Set the maximum line width
max_width = 100

# Use 4 spaces for indentation
tab_spaces = 4

# Use the default set of rules
# Uncomment the following line to enable custom rules
# custom_rules = true

## Nightly only, but preferrable
# brace_style = "PreferSameLine"
# enum_discrim_align_threshold = 30