[package]
name = "atrium-cli"
version = "0.1.0"
edition = "2021"
authors = ["sugyan <sugi1982+github@gmail.com>"]

[dependencies]
atrium-api = { path = "../atrium-api" }
atrium-xrpc = { path = "../atrium-xrpc" }
chrono = "0.4.24"
clap = { version = "4.2.4", features = ["derive"] }
serde = "1.0.160"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.7.3"
