[package]
name = "concurrent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atrium-api = "0.14"
atrium-xrpc-client = "0.2"
clap = { version = "4.4.7", features = ["derive"] }
futures = "0.3.29"
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
